# Generated by Django 3.2.14 on 2022-08-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_hobby_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hobby_tb',
        ),
    ]
