# Generated by Django 3.2.14 on 2022-08-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0008_seasoncountry_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='agefactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimumage', models.IntegerField()),
                ('maximumage', models.IntegerField()),
                ('factorname', models.CharField(max_length=20)),
            ],
        ),
    ]
