# Generated by Django 3.2.14 on 2022-08-05 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0005_message_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='trash_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('messageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteuser.message_tb')),
                ('receiverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteuser.register_tb')),
            ],
        ),
    ]
