# Generated by Django 3.2.14 on 2022-08-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0009_agefactor_tb'),
        ('siteuser', '0010_customerfactor_tb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customerfactor_tb',
            new_name='customeragefactor_tb',
        ),
    ]
